version: '3.1'

services:
  dbpostgres:
    image: postgres
    volumes:
      - pgData:/data/db
      - ./data/postgres:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: str
      POSTGRES_PASSWORD: K@tia
      POSTGRES_DB: amazon_test

volumes:
  pgData:
